### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by Robmobius** [enguerr/MauticBeefreeBundle#1]
Installed as per instructions on both ver 3 and ver 2.16.2 and nothing shows up in the manage plugins section of Mautic. Tried clearing cache, no help. 

What am I doing wrong?

**Comment by enguerr** [comment]
Hello, this plugin is not operational now.
I 'll let you know when it's ready.

**Comment by ShareBtech** [comment]
Hey enguerr

This is going to be super cool feature.  Looking forward to seeing it work.
I managed to install the plugin and see it in plugins, also see the BeeFree button
![image](https://user-images.githubusercontent.com/59197832/85551433-acab2380-b62a-11ea-9f44-32154212c69f.png)

Unfortunately nothing happens yet (I am reading your previous comment that it is not operational :-) ).  I tried on chrome and safari.
Let me know when operational will be happy to test

**Comment by enguerr** [comment]
Hello,
I plan to release an alpha version next week. stay tune :)
You can create API et SECRET on plugin.beefree.io (it's free) and wait juste a few days.
I've currently some problems with EmailController overriding and repository access from plugin....

**Comment by enguerr** [comment]
You can try it now.
You need to register an app to freebee.io first. 
it's free.

**Comment by ShareBtech** [comment]
Hey Good morning.  I ran everything this morning and all seems to be working.  Only problem is it opens BeeFree in French :-D.  But super cool.  Well done

**Comment by enguerr** [comment]
ok thank you for the feedback!
can you create an issue for the beefree language ?
i will plan some sprint...

**Comment by enguerr** [comment]
I close this issue as resolved ;)
