### ISSUE TITLE
Grey screen after clicking on beefree button

### ISSUE THREAD

**Issue by jos0405** [enguerr/MauticBeefreeBundle#2]
Hi,
Upon clicking on the beefree button in the email builder and new window pops up.
url example:
https://mautic.tld/s/beefree/email/builder/new_11d16e76e751d76bc6dcac09d54774aca8990c47?template=blank&t=1592381969770

All the js seems to be loaded, but the page doesn't render.
In the attached html the domain name is replaced.
Thx for checking.

Mautic version 2.16.2

[popup.txt](https://github.com/enguerr/MauticBeefreeBundle/files/4791257/popup.txt)

**Comment by enguerr** [comment]
please wait few days more ... i will make a relase asap

**Comment by jos0405** [comment]
Thank you, I appreciate you doing it.

**Comment by enguerr** [comment]
You can try it now.
Register an app  to beefree.io first.
Give me your feedback.

**Comment by jos0405** [comment]
Good job. This issue is solved.
