### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by ShareBtech** [enguerr/MauticBeefreeBundle#3]
Hi,

Currently the BeeFree interface defaults to french.  
Would be good to have language preference or default to english

**Comment by enguerr** [comment]
81ca594bdab100234f0332764a865ff2d5c0d79e

**Comment by enguerr** [comment]
you can try a git pull to have en_US langage by default.

**Comment by enguerr** [comment]
language en_Us / fr supported.
If you want another language, please ping me (i need to tranform string format for locale for ex: en_US => en-US)
